parameters:
  snyk_token: ''
  
jobs:
- job: Snyk_SCA_Scan_Job
  steps:
  - script: |
      SNYK_TOKEN=$(snyk_token)
      export SNYK_TOKEN
      mvn snyk:test -fn 
    displayName: "Integrate SCA scan using Snyk in ADO DevSecOps Pipeline"
